name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build Windows
        id: buildw
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: museu-virtual
          preset: windows
          projectDir: src
      - name: Build Linux
        id: buildl
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: museu-virtual
          preset: linux
          projectDir: src
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/${{ steps.buildw.outputs.build }}
            ${{ github.workspace }}/${{ steps.buildl.outputs.build }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
