name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Platforms to export to, can be [linux, windows, mac]
    strategy:
      matrix:
        platform: [linux, windows]
        
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: museu-virtual
          preset: ${{ matrix.platform }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/${{ steps.build.outputs.build }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
